const test={
  chaosMeter: 1,
  connectionDeck: [{
  cardType: "connection",
  misinfoType: "community",
  sourceName: "gym"
}, {
  cardType: "connection",
  misinfoType: "social",
  sourceName: "reddit"
}, {
  cardType: "connection",
  misinfoType: "community",
  sourceName: "university"
}, {
  cardType: "viral",
  misinfoType: null,
  sourceName: null
}, {
  cardType: "connection",
  misinfoType: "social",
  sourceName: "twitter"
}, {
  cardType: "connection",
  misinfoType: "relations",
  sourceName: "auntie"
}, {
  cardType: "connection",
  misinfoType: "relations",
  sourceName: "guy at the bus stop"
}, {
  cardType: "connection",
  misinfoType: "community",
  sourceName: "hair salon"
}, {
  cardType: "connection",
  misinfoType: "community",
  sourceName: "asda"
}, {
  cardType: "viral",
  misinfoType: null,
  sourceName: null
}, {
  cardType: "connection",
  misinfoType: "relations",
  sourceName: "crazy dave"
}, {
  cardType: "connection",
  misinfoType: "community",
  sourceName: "high school"
}, {
  cardType: "connection",
  misinfoType: "community",
  sourceName: "pub"
}, {
  cardType: "connection",
  misinfoType: "relations",
  sourceName: "opinionated grandpa"
}, {
  cardType: "connection",
  misinfoType: "community",
  sourceName: "taxi"
}, {
  cardType: "connection",
  misinfoType: "relations",
  sourceName: "cousin"
}, {
  cardType: "connection",
  misinfoType: "social",
  sourceName: "whatsapp"
}, {
  cardType: "connection",
  misinfoType: "relations",
  sourceName: "evil ex"
}, {
  cardType: "connection",
  misinfoType: "social",
  sourceName: "intagram"
}, {
  cardType: "connection",
  misinfoType: "social",
  sourceName: "illuminati"
}, {
  cardType: "viral",
  misinfoType: null,
  sourceName: null
}, {
  cardType: "connection",
  misinfoType: "relations",
  sourceName: "fran from hr"
}, {
  cardType: "connection",
  misinfoType: "social",
  sourceName: "tik-tok"
}],
  gameLost: false,
  gameWon: false,
  misinformation: {
    community: { ... },
    relations: { ... },
    social: { ... }
  },
  misinformationDeckActive: [{
  cardType: "misinformation",
  misinfoType: "community",
  sourceName: "pub"
}, {
  cardType: "misinformation",
  misinfoType: "relations",
  sourceName: "cousin"
}, {
  cardType: "misinformation",
  misinfoType: "relations",
  sourceName: "evil ex"
}, {
  cardType: "misinformation",
  misinfoType: "relations",
  sourceName: "auntie"
}, {
  cardType: "misinformation",
  misinfoType: "community",
  sourceName: "taxi"
}, {
  cardType: "misinformation",
  misinfoType: "relations",
  sourceName: "guy at the bus stop"
}, {
  cardType: "misinformation",
  misinfoType: "social",
  sourceName: "facebook"
}, {
  cardType: "misinformation",
  misinfoType: "social",
  sourceName: "tik-tok"
}, {
  cardType: "misinformation",
  misinfoType: "relations",
  sourceName: "opinionated grandpa"
}, {
  cardType: "misinformation",
  misinfoType: "social",
  sourceName: "intagram"
}, {
  cardType: "misinformation",
  misinfoType: "social",
  sourceName: "reddit"
}, {
  cardType: "misinformation",
  misinfoType: "relations",
  sourceName: "fran from hr"
}, {
  cardType: "misinformation",
  misinfoType: "relations",
  sourceName: "crazy dave"
}, {
  cardType: "misinformation",
  misinfoType: "social",
  sourceName: "twitter"
}, {
  cardType: "misinformation",
  misinfoType: "community",
  sourceName: "gym"
}, {
  cardType: "misinformation",
  misinfoType: "community",
  sourceName: "local cult"
}, {
  cardType: "misinformation",
  misinfoType: "community",
  sourceName: "high school"
}, {
  cardType: "misinformation",
  misinfoType: "social",
  sourceName: "illuminati"
}, {
  cardType: "misinformation",
  misinfoType: "social",
  sourceName: "youtube"
}, {
  cardType: "misinformation",
  misinfoType: "social",
  sourceName: "whatsapp"
}, {
  cardType: "misinformation",
  misinfoType: "community",
  sourceName: "university"
}, {
  cardType: "misinformation",
  misinfoType: "community",
  sourceName: "hair salon"
}, {
  cardType: "misinformation",
  misinfoType: "relations",
  sourceName: "mother-in-law"
}, {
  cardType: "misinformation",
  misinfoType: "community",
  sourceName: "asda"
}],
  misinformationDeckPassive: [[circular object Object], [circular object Object], [circular object Object], [circular object Object], [circular object Object], [circular object Object], [circular object Object]],
  players: [{
  cardHandOverflow: false,
  cards: [{
  cardType: "connection",
  misinfoType: "social",
  sourceName: "youtube"
}, {
  cardType: "connection",
  misinfoType: "community",
  sourceName: "local cult"
}],
  currentSource: "University",
  id: "1234",
  isCurrent: true,
  name: "Player 1",
  pawnColor: "green"
}, {
  cardHandOverflow: false,
  cards: [[circular object Object], [circular object Object]],
  currentSource: "University",
  id: "5678",
  isCurrent: false,
  name: "Player 2",
  pawnColor: "purple"
}],
  sources: [{
  canClearCommunity: false,
  canClearRelations: false,
  canClearSocial: false,
  canDebunk: [],
  canLogOff: false,
  canLogOn: false,
  canMove: false,
  canShare: [],
  markers_community: 0,
  markers_relations: 0,
  markers_social: 0,
  misinfoType: "community",
  name: "high school"
}, {
  canClearCommunity: false,
  canClearRelations: false,
  canClearSocial: false,
  canDebunk: [],
  canLogOff: false,
  canLogOn: false,
  canMove: false,
  canShare: [],
  markers_community: 3,
  markers_relations: 0,
  markers_social: 0,
  misinfoType: "community",
  name: "taxi"
}, {
  canClearCommunity: false,
  canClearRelations: false,
  canClearSocial: false,
  canDebunk: [],
  canLogOff: false,
  canLogOn: false,
  canMove: false,
  canShare: [],
  markers_community: 0,
  markers_relations: 0,
  markers_social: 0,
  misinfoType: "community",
  name: "local cult"
}, {
  canClearCommunity: false,
  canClearRelations: false,
  canClearSocial: false,
  canDebunk: [],
  canLogOff: false,
  canLogOn: false,
  canMove: false,
  canShare: [],
  markers_community: 3,
  markers_relations: 0,
  markers_social: 0,
  misinfoType: "community",
  name: "pub"
}, {
  canClearCommunity: false,
  canClearRelations: false,
  canClearSocial: false,
  canDebunk: [],
  canLogOff: false,
  canLogOn: false,
  canMove: false,
  canShare: [],
  markers_community: 0,
  markers_relations: 0,
  markers_social: 0,
  misinfoType: "community",
  name: "university"
}, {
  canClearCommunity: false,
  canClearRelations: false,
  canClearSocial: false,
  canDebunk: [],
  canLogOff: false,
  canLogOn: false,
  canMove: false,
  canShare: [],
  markers_community: 0,
  markers_relations: 0,
  markers_social: 1,
  misinfoType: "community",
  name: "hair salon"
}, {
  canClearCommunity: false,
  canClearRelations: false,
  canClearSocial: false,
  canDebunk: [],
  canLogOff: false,
  canLogOn: false,
  canMove: false,
  canShare: [],
  markers_community: 0,
  markers_relations: 0,
  markers_social: 0,
  misinfoType: "community",
  name: "gym"
}, {
  canClearCommunity: false,
  canClearRelations: false,
  canClearSocial: false,
  canDebunk: [],
  canLogOff: false,
  canLogOn: false,
  canMove: false,
  canShare: [],
  markers_community: 3,
  markers_relations: 0,
  markers_social: 0,
  misinfoType: "community",
  name: "asda"
}, {
  canClearCommunity: false,
  canClearRelations: false,
  canClearSocial: false,
  canDebunk: [],
  canLogOff: false,
  canLogOn: false,
  canMove: false,
  canShare: [],
  markers_community: 0,
  markers_relations: 1,
  markers_social: 0,
  misinfoType: "relations",
  name: "auntie"
}, {
  canClearCommunity: false,
  canClearRelations: false,
  canClearSocial: false,
  canDebunk: [],
  canLogOff: false,
  canLogOn: false,
  canMove: false,
  canShare: [],
  markers_community: 0,
  markers_relations: 0,
  markers_social: 0,
  misinfoType: "relations",
  name: "mother-in-law"
}, {
  canClearCommunity: false,
  canClearRelations: false,
  canClearSocial: false,
  canDebunk: [],
  canLogOff: false,
  canLogOn: false,
  canMove: false,
  canShare: [],
  markers_community: 0,
  markers_relations: 1,
  markers_social: 0,
  misinfoType: "relations",
  name: "cousin"
}, {
  canClearCommunity: false,
  canClearRelations: false,
  canClearSocial: false,
  canDebunk: [],
  canLogOff: false,
  canLogOn: false,
  canMove: false,
  canShare: [],
  markers_community: 0,
  markers_relations: 0,
  markers_social: 0,
  misinfoType: "relations",
  name: "fran from hr"
}, {
  canClearCommunity: false,
  canClearRelations: false,
  canClearSocial: false,
  canDebunk: [],
  canLogOff: false,
  canLogOn: false,
  canMove: false,
  canShare: [],
  markers_community: 0,
  markers_relations: 2,
  markers_social: 0,
  misinfoType: "relations",
  name: "evil ex"
}, {
  canClearCommunity: false,
  canClearRelations: false,
  canClearSocial: false,
  canDebunk: [],
  canLogOff: false,
  canLogOn: false,
  canMove: false,
  canShare: [],
  markers_community: 0,
  markers_relations: 0,
  markers_social: 0,
  misinfoType: "relations",
  name: "guy at the bus stop"
}, {
  canClearCommunity: false,
  canClearRelations: false,
  canClearSocial: false,
  canDebunk: [],
  canLogOff: false,
  canLogOn: false,
  canMove: false,
  canShare: [],
  markers_community: 0,
  markers_relations: 0,
  markers_social: 0,
  misinfoType: "relations",
  name: "crazy dave"
}, {
  canClearCommunity: false,
  canClearRelations: false,
  canClearSocial: false,
  canDebunk: [],
  canLogOff: false,
  canLogOn: false,
  canMove: false,
  canShare: [],
  markers_community: 0,
  markers_relations: 0,
  markers_social: 0,
  misinfoType: "relations",
  name: "opinionated grandpa"
}, {
  canClearCommunity: false,
  canClearRelations: false,
  canClearSocial: false,
  canDebunk: [],
  canLogOff: false,
  canLogOn: false,
  canMove: false,
  canShare: [],
  markers_community: 0,
  markers_relations: 0,
  markers_social: 0,
  misinfoType: "social",
  name: "illuminati"
}, {
  canClearCommunity: false,
  canClearRelations: false,
  canClearSocial: false,
  canDebunk: [],
  canLogOff: false,
  canLogOn: false,
  canMove: false,
  canShare: [],
  markers_community: 0,
  markers_relations: 0,
  markers_social: 0,
  misinfoType: "social",
  name: "youtube"
}, {
  canClearCommunity: false,
  canClearRelations: false,
  canClearSocial: false,
  canDebunk: [],
  canLogOff: false,
  canLogOn: false,
  canMove: false,
  canShare: [],
  markers_community: 0,
  markers_relations: 0,
  markers_social: 1,
  misinfoType: "social",
  name: "intagram"
}, {
  canClearCommunity: false,
  canClearRelations: false,
  canClearSocial: false,
  canDebunk: [],
  canLogOff: false,
  canLogOn: false,
  canMove: false,
  canShare: [],
  markers_community: 0,
  markers_relations: 0,
  markers_social: 2,
  misinfoType: "social",
  name: "facebook"
}, {
  canClearCommunity: false,
  canClearRelations: false,
  canClearSocial: false,
  canDebunk: [],
  canLogOff: false,
  canLogOn: false,
  canMove: false,
  canShare: [],
  markers_community: 0,
  markers_relations: 0,
  markers_social: 1,
  misinfoType: "social",
  name: "reddit"
}, {
  canClearCommunity: false,
  canClearRelations: false,
  canClearSocial: false,
  canDebunk: [],
  canLogOff: false,
  canLogOn: false,
  canMove: false,
  canShare: [],
  markers_community: 0,
  markers_relations: 0,
  markers_social: 0,
  misinfoType: "social",
  name: "twitter"
}, {
  canClearCommunity: false,
  canClearRelations: false,
  canClearSocial: false,
  canDebunk: [],
  canLogOff: false,
  canLogOn: false,
  canMove: false,
  canShare: [],
  markers_community: 0,
  markers_relations: 0,
  markers_social: 0,
  misinfoType: "social",
  name: "whatsapp"
}, {
  canClearCommunity: false,
  canClearRelations: false,
  canClearSocial: false,
  canDebunk: [],
  canLogOff: false,
  canLogOn: false,
  canMove: false,
  canShare: [],
  markers_community: 0,
  markers_relations: 0,
  markers_social: 0,
  misinfoType: "social",
  name: "tik-tok"
}],
  spreadLevel: 1,
  turnMovesLeft: 0,
  turnOrder: []
}