[
  {
    canClearCommunity: false,
    canClearRelations: false,
    canClearSocial: false,
    canDebunk: [],
    canLogOff: false,
    canLogOn: false,
    canMove: false,
    canShare: [],
    markers_community: 3,
    markers_relations: 0,
    markers_social: 0,
    misinfoType: 'community',
    name: 'high school',
  },
  {
    canClearCommunity: false,
    canClearRelations: false,
    canClearSocial: false,
    canDebunk: [],
    canLogOff: false,
    canLogOn: false,
    canMove: false,
    canShare: [],
    markers_community: 3,
    markers_relations: 0,
    markers_social: 0,
    misinfoType: 'community',
    name: 'taxi',
  },
  {
    canClearCommunity: false,
    canClearRelations: false,
    canClearSocial: false,
    canDebunk: [],
    canLogOff: false,
    canLogOn: false,
    canMove: false,
    canShare: [],
    markers_community: 2,
    markers_relations: 0,
    markers_social: 0,
    misinfoType: 'community',
    name: 'local cult',
  },
  {
    canClearCommunity: false,
    canClearRelations: false,
    canClearSocial: false,
    canDebunk: [],
    canLogOff: false,
    canLogOn: false,
    canMove: false,
    canShare: [],
    markers_community: 2,
    markers_relations: 0,
    markers_social: 0,
    misinfoType: 'community',
    name: 'pub',
  },
  {
    canClearCommunity: false,
    canClearRelations: false,
    canClearSocial: false,
    canDebunk: [],
    canLogOff: false,
    canLogOn: false,
    canMove: false,
    canShare: [],
    markers_community: 0,
    markers_relations: 0,
    markers_social: 0,
    misinfoType: 'community',
    name: 'university',
  },
  {
    canClearCommunity: false,
    canClearRelations: false,
    canClearSocial: false,
    canDebunk: [],
    canLogOff: false,
    canLogOn: false,
    canMove: false,
    canShare: [],
    markers_community: 0,
    markers_relations: 0,
    markers_social: 0,
    misinfoType: 'community',
    name: 'hair salon',
  },
  {
    canClearCommunity: false,
    canClearRelations: false,
    canClearSocial: false,
    canDebunk: [],
    canLogOff: false,
    canLogOn: false,
    canMove: false,
    canShare: [],
    markers_community: 0,
    markers_relations: 0,
    markers_social: 0,
    misinfoType: 'community',
    name: 'gym',
  },
  {
    canClearCommunity: false,
    canClearRelations: false,
    canClearSocial: false,
    canDebunk: [],
    canLogOff: false,
    canLogOn: false,
    canMove: false,
    canShare: [],
    markers_community: 1,
    markers_relations: 0,
    markers_social: 0,
    misinfoType: 'community',
    name: 'asda',
  },
  {
    canClearCommunity: false,
    canClearRelations: false,
    canClearSocial: false,
    canDebunk: [],
    canLogOff: false,
    canLogOn: false,
    canMove: false,
    canShare: [],
    markers_community: 0,
    markers_relations: 0,
    markers_social: 0,
    misinfoType: 'relations',
    name: 'auntie',
  },
  {
    canClearCommunity: false,
    canClearRelations: false,
    canClearSocial: false,
    canDebunk: [],
    canLogOff: false,
    canLogOn: false,
    canMove: false,
    canShare: [],
    markers_community: 0,
    markers_relations: 0,
    markers_social: 0,
    misinfoType: 'relations',
    name: 'mother-in-law',
  },
  {
    canClearCommunity: false,
    canClearRelations: false,
    canClearSocial: false,
    canDebunk: [],
    canLogOff: false,
    canLogOn: false,
    canMove: false,
    canShare: [],
    markers_community: 0,
    markers_relations: 0,
    markers_social: 0,
    misinfoType: 'relations',
    name: 'cousin',
  },
  {
    canClearCommunity: false,
    canClearRelations: false,
    canClearSocial: false,
    canDebunk: [],
    canLogOff: false,
    canLogOn: false,
    canMove: false,
    canShare: [],
    markers_community: 0,
    markers_relations: 0,
    markers_social: 0,
    misinfoType: 'relations',
    name: 'fran from hr',
  },
  {
    canClearCommunity: false,
    canClearRelations: false,
    canClearSocial: false,
    canDebunk: [],
    canLogOff: false,
    canLogOn: false,
    canMove: false,
    canShare: [],
    markers_community: 0,
    markers_relations: 0,
    markers_social: 0,
    misinfoType: 'relations',
    name: 'evil ex',
  },
  {
    canClearCommunity: false,
    canClearRelations: false,
    canClearSocial: false,
    canDebunk: [],
    canLogOff: false,
    canLogOn: false,
    canMove: false,
    canShare: [],
    markers_community: 0,
    markers_relations: 0,
    markers_social: 0,
    misinfoType: 'relations',
    name: 'guy at the bus stop',
  },
  {
    canClearCommunity: false,
    canClearRelations: false,
    canClearSocial: false,
    canDebunk: [],
    canLogOff: false,
    canLogOn: false,
    canMove: false,
    canShare: [],
    markers_community: 0,
    markers_relations: 0,
    markers_social: 0,
    misinfoType: 'relations',
    name: 'crazy dave',
  },
  {
    canClearCommunity: false,
    canClearRelations: false,
    canClearSocial: false,
    canDebunk: [],
    canLogOff: false,
    canLogOn: false,
    canMove: false,
    canShare: [],
    markers_community: 0,
    markers_relations: 0,
    markers_social: 0,
    misinfoType: 'relations',
    name: 'opinionated grandpa',
  },
  {
    canClearCommunity: false,
    canClearRelations: false,
    canClearSocial: false,
    canDebunk: [],
    canLogOff: false,
    canLogOn: false,
    canMove: false,
    canShare: [],
    markers_community: 0,
    markers_relations: 0,
    markers_social: 0,
    misinfoType: 'social',
    name: 'illuminati',
  },
  {
    canClearCommunity: false,
    canClearRelations: false,
    canClearSocial: false,
    canDebunk: [],
    canLogOff: false,
    canLogOn: false,
    canMove: false,
    canShare: [],
    markers_community: 0,
    markers_relations: 0,
    markers_social: 0,
    misinfoType: 'social',
    name: 'youtube',
  },
  {
    canClearCommunity: false,
    canClearRelations: false,
    canClearSocial: false,
    canDebunk: [],
    canLogOff: false,
    canLogOn: false,
    canMove: false,
    canShare: [],
    markers_community: 0,
    markers_relations: 0,
    markers_social: 0,
    misinfoType: 'social',
    name: 'intagram',
  },
  {
    canClearCommunity: false,
    canClearRelations: false,
    canClearSocial: false,
    canDebunk: [],
    canLogOff: false,
    canLogOn: false,
    canMove: false,
    canShare: [],
    markers_community: 0,
    markers_relations: 0,
    markers_social: 0,
    misinfoType: 'social',
    name: 'facebook',
  },
  {
    canClearCommunity: false,
    canClearRelations: false,
    canClearSocial: false,
    canDebunk: [],
    canLogOff: false,
    canLogOn: false,
    canMove: false,
    canShare: [],
    markers_community: 0,
    markers_relations: 0,
    markers_social: 3,
    misinfoType: 'social',
    name: 'reddit',
  },
  {
    canClearCommunity: false,
    canClearRelations: false,
    canClearSocial: false,
    canDebunk: [],
    canLogOff: false,
    canLogOn: false,
    canMove: false,
    canShare: [],
    markers_community: 0,
    markers_relations: 0,
    markers_social: 0,
    misinfoType: 'social',
    name: 'twitter',
  },
  {
    canClearCommunity: false,
    canClearRelations: false,
    canClearSocial: false,
    canDebunk: [],
    canLogOff: false,
    canLogOn: false,
    canMove: false,
    canShare: [],
    markers_community: 0,
    markers_relations: 0,
    markers_social: 0,
    misinfoType: 'social',
    name: 'whatsapp',
  },
  {
    canClearCommunity: false,
    canClearRelations: false,
    canClearSocial: false,
    canDebunk: [],
    canLogOff: false,
    canLogOn: false,
    canMove: false,
    canShare: [],
    markers_community: 0,
    markers_relations: 0,
    markers_social: 1,
    misinfoType: 'social',
    name: 'tik-tok',
  },
];
